server:
  port: 9191
  servlet:
    context-path: /auth-api
    session:
      cookie:
        http-only: true
        secure: false

###################################  SQLSerer Database as persistent Database  ##############################
spring:
  application:
    name: auth-server
  devtools:
    restart:
      enabled: true
#  profiles:
#    active: default
  main:
    banner-mode: off
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
      
  thymeleaf:
     cache: false
  sleuth:   
     tx: 
        enabled: false

#jdbc:
#   url: jdbc:sqlserver://192.168.17.1:1433;databaseName=VST_DMS
#   username: admin
#   password: hrsl@2024#
   
#jdbc:
#   url: jdbc:sqlserver://172.16.1.65:1433;databaseName=VST_DMS_PROD
#   username: sa
#   password: VST.2022#

jdbc:
   url: jdbc:sqlserver://192.9.200.52:1433;databaseName=VST_DMS
   username: sa
   password: VST.2022#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true
    #lease-expiration-duration-in-seconds: 1
    #lease-renewal-interval-in-seconds: 2

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
   upload-dir: 
      Temp: C:/VST-DMS-APPS/FILES/Temp/
      Main: C:/VST-DMS-APPS/FILES/

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  endpoint:
    auditevents:
      enabled: true

security:
   signing-key: MaYzkSjmkzPC57L
   encoding-strength: 256
   security-realm: HiTeChRealm