

jdbc:
   url: jdbc:sqlserver://172.16.1.65:1433;databaseName=VST_DMS_PROD
   username: sa
   password: VST.2022#
   

eureka:
  client:
    service-url:
      defaultZone: http://vstdms.vstshakti.in:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true
    #lease-expiration-duration-in-seconds: 1
    #lease-renewal-interval-in-seconds: 2
    
    
#oauth2 configuration
security:
   oauth2:
      resource: 
         token-info-uri: http://vstdms.vstshakti.in:9191/auth-api/oauth/check_token
      client:
         client-id: vst-dms-view-client
         client-secret: cnhindglobal
         
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
   upload-dir: 
      Temp: /var/VST-DMS-APPS/FILES/Temp/
      Main: /var/VST-DMS-APPS/FILES/

spring:
   rabbitmq:
      host: vstdms.vstshakti.in
      port: 5672
      username: guest
      password: Vst@2022#
# rabbitmq
# \****confirms****** P -> Exchange
      publisher-confirms: true
# \****returnedMessage**** Exchange -> Queue
      publisher-returns: true
# \*****(ack) Queue -> C
      listener:
         simple:
            acknowledge-mode: manual
            prefetch: 100
            
mail_forgot_password:
   queue: forgotpassword.queue
   exchange: forgotpassword.exchange
   routing_key: forgot.password.routing.key
mail_change_password:
   queue: changepassword.queue
   exchange: changepassword.exchange
   routing_key: changepassword.routing.key
mail_create_enq:
   queue: enqCreate.queue
   exchange: enqCreate.exchange
   routing_key: enqCreate.routing.key
mail_validated_enq:
   queue: enqvalidated.queue
   exchange: enqvalidated.exchange
   routing_key: enqvalidated.routing.key
mail_followup_enq:
   queue: followupenq.queue
   exchange: followupenq.exchange
   routing_key: followupenq.routing.key
mail_retailfollowup_enq:
   queue: retailfollowupenq.queue
   exchange: retailfollowupenq.exchange
   routing_key: retailfollowupenq.routing.key