server:
  port: 9090
  servlet:
    context-path: /administration
    session:
      cookie:
        http-only: true
        secure: false
        
  error: 
    include-message: always
    include-binding-errors: always

#logging: 
#   level: 
#      org.springframework.web: ERROR
#      com.hitech.dms: DEBUG

###################################  SQLSerer Database as persistent Database  ##############################
spring:
  application:
    name: administration-server
  devtools:
    restart:
      enabled: false
#  profiles:
#    active: default
  main:
    banner-mode: off
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
      
  thymeleaf:
     cache: false
     
  servlet:
     multipart:
        enabled: true
        # Threshold after which files are written to disk.
        file-size-threshold: 2KB
        # Max file size.
        max-file-size: 200MB
        # Max Request Size
        max-request-size: 215MB
  #jpa: 
     #hibernate: 
        #use-new-id-generator-mappings: false

#jdbc:
#   url: jdbc:sqlserver://192.168.17.1:1433;databaseName=VST_DMS
#   username: admin
#   password: hrsl@2017#
jdbc:
   url: jdbc:sqlserver://192.9.200.52:1433;databaseName=VST_DMS
   username: sa
   password: VST.2022#   
   
 #################SUNIL###################################################
jdbcsecondarydb:
   url: jdbc:sqlserver://192.9.200.52:1433;databaseName=VST_DMS_STAGING
   username: sa
   password: VST.2022#
#################END#######################################################  
#jdbc:
#   url: jdbc:sqlserver://172.16.1.100:1433;databaseName=VST_DMS_PROD
#   username: sa
#   password: VST.2022#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true
    #lease-expiration-duration-in-seconds: 1
    #lease-renewal-interval-in-seconds: 2

#oauth2 configuration
security:
   oauth2:
      resource: 
         token-info-uri: http://localhost:9191/auth-api/oauth/check_token
      client:
         client-id: vst-dms-view-client
         client-secret: cnhindglobal

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
   upload-dir: 
      Temp: C:/VST-DMS-APPS/FILES/Temp/
      Main: C:/VST-DMS-APPS/FILES/
      AprMappingTemplate: C:/VST-DMS-APPS/Template/APR Template/
      AddVillageTemp: C:/VST-DMS-APPS/template/add-village/
      SfrMappingTemplate: C:/VST-DMS-APPS/Template/SFR Template/
      

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  endpoint:
    auditevents:
      enabled: true
#health,info,refresh
         
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: BASIC
      postFeignClient:
        loggerLevel: FULL
        
springdoc:
  version: '@springdoc.version@'
