server:
  port: 9999
  servlet:
    context-path: /emailService
    session:
      cookie:
        http-only: true
        secure: false
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: service-email
  devtools:
    restart:
      enabled: false
  main:
    banner-mode: 'off'
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: 192.9.200.204
    port: 587
    username: itsupport@vsttillers.com
    password: vst.2017
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: '5000'
          timeout: '5000'
          writetimeout: '5000'
          starttls:
            enable: true
            required: true

jdbc:
  url: 'jdbc:sqlserver://192.168.17.1:1433;databaseName=VST_DMS'
  username: admin
  password: 'hrsl@2017#'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
    register-with-eureka: true
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true

security:
  oauth2:
    resource:
      token-info-uri: 'http://localhost:9191/auth-api/oauth/check_token'
    client:
      client-id: vst-dms-view-client
      client-secret: cnhindglobal

file:
  upload-dir:
    Temp: 'C:/VST-DMS-APPS/FILES/Temp/'
    Main: 'C:/VST-DMS-APPS/FILES/'

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'env,beans'
  endpoint:
    auditevents:
      enabled: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: BASIC
      postFeignClient:
        loggerLevel: FULL

springdoc:
  version: '@springdoc.version@'
